utils::globalVariables(c(
  'last_sync','polis_update_value', 'last_user', 'x', 'ADM0_GUID', 'ADM1_GUID', 'ADM1_NAME',
  'ADM2_NAME', 'API_Name', 'Admin 2 Guid',
  'Admin0OfficialName', 'Admin1OfficialName', 'Admin2OfficialName', 'Area Population',
  'DateFrom', 'Doses', 'EPID', 'Env Sample Manual Edit Id', 'GUID', 'Id',
  'Number of Doses', 'SIA Sub-Activity Code', 'SIASubActivityCode', 'Sample Id',
  'Site Code', 'Site Name', 'Table', 'Targeted Population', 'Virus ID', 'Virus Sequenced',
  'Virus Type(s)', 'active.year.01', 'name', ':=',
  '.', 'ADM0_NAME', 'ADM0_NAME.rep', 'Admin1GUID', 'Admin2GUID', 'ISO_3_CODE',
  'SHAPE', 'activity.end.date', 'activity.start.date', 'adm0guid', 'adm1guid',
  'adm2guid', 'admin.0', 'admin.0.guid', 'admin.1', 'admin.1.guid', 'admin.1.officialname',
  'admin.2', 'admin.2.guid', 'admin.2.officialname', 'admin.coverage.%', 'admin0guid',
  'admin1', 'admin1guid', 'admin2', 'admin2guid', 'advanced.notification', 'afp_dup',
  'age.group', 'age.group.%', 'area.targeted.%', 'calculated.age.(months)',
  'camp.diff.days', 'case.miss.guid', 'categorical_response_set.x', 'categorical_response_set.y',
  'cdc.classification.all', 'character.n_unique', 'classification', 'classificationvdpv',
  'clinical.admitted.date', 'collect.date', 'collect.yr', 'collection.date',
  'combine.distinct.01', 'congo_wild1', 'country', 'country.population.%', 'ctime',
  'ctry', 'ctry.guid', 'dataset.lab', 'date.notification.to.hq', 'date.onset',
  'dateinvest', 'datenotificationtohq', 'datenotify', 'dateonset', 'datestool1',
  'datestool2', 'diagnosis.final', 'diff.distinct.01', 'dist.guid', 'doses',
  'doses.total', 'dup', 'dup_epid', 'emergence.group', 'emergence.group(s)',
  'emergencegroup', 'empty.01', 'env.sample.id', 'env.sample.manual.edit.id',
  'epid', 'epid.in.polis', 'es.dups', 'final.cell.culture.result', 'followup.date',
  'head', 'hot.case', 'im.loaded', 'in_new_not_old', 'in_old_not_new',
  'investigation.date', 'lat', 'latitude', 'linked.outbreak(s)', 'lng', 'lon',
  'longitude', 'lqas.loaded', 'match01', 'missing.guid', 'new_categorical_response_set',
  'no_match', 'notification.date', 'nperarm', 'nt.changes', 'ntchanges', 'old.distinct.01',
  'old_categorical_response_set', 'ontonot', 'ontonot.14', 'ontonot.60', 'ontostool2',
  'ontostool2.03', 'paralysis.asymmetric', 'paralysis.onset.fever', 'paralysis.rapid.progress',
  'person.sex', 'place.admin.0', 'place.admin.1', 'place.admin.2', 'poliovirustypes',
  'polis.case.id', 'polis.latitude', 'polis.longitude', 'pons.epid', 'prov.guid',
  'region.name', 'response', 'results.seq.date.to.program', 'sabin', 'same',
  'sample.condition', 'sample.id', 'sia.sub-activity.code', 'sia.sub.activity.code',
  'site.code', 'site.id', 'site.name', 'skim_type', 'skim_variable', 'status',
  'stool.1.collection.date', 'stool.1.condition', 'stool.2.collection.date', 'stool.2.condition',
  'stool.adequacy', 'stool.date.sent.to.ic.lab', 'stool.date.sent.to.lab', 'sub-activity.end.date',
  'sub-activity.initial.planned.date', 'sub-activity.last.updated.date', 'sub-activity.start.date',
  'sub.activity.end.date', 'sub.activity.start.date', 'surveillance.type', 'surveillancetypename',
  'timeliness.01', 'vaccine.source', 'vaccine.type', 'var_class.x', 'var_class.y', 'var_name',
  'variable', 'vdpv.classification(s)', 'vdpv.classification.id(s)', 'virus.cluster',
  'virus.cluster(s)', 'virus.date', 'virus.id', 'virus.type', 'virus.type(s)', 'virus.type.01',
  'virus_dup', 'virustype', 'virustypename', 'vtype', 'vtype.fixed', 'wastage.factor',
  'who.region', 'whoregion', 'write.csv', 'wrongAdmin1GUID', 'wrongAdmin2GUID', 'yr.sia', 'yr.st', 'yronset'
))
